# Generated by Django 5.2.8 on 2025-11-30 11:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("storefront_url", models.URLField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                (
                    "res_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to existing ResUsers entry (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendors",
                        to="home.resusers",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Django auth user who manages this vendor",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendor",
                "verbose_name_plural": "Vendors",
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="VendorBankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("iban", models.CharField(blank=True, max_length=64)),
                (
                    "vendor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_detail",
                        to="multivendor.vendor",
                    ),
                ),
            ],
        ),
    ]
