# Generated by Django 5.2.8 on 2025-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(db_comment="Type")),
                ("name", models.JSONField(db_comment="Account Name")),
                (
                    "code_store",
                    models.JSONField(blank=True, db_comment="Code Store", null=True),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, db_comment="Internal Notes", null=True
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(blank=True, db_comment="Deprecated", null=True),
                ),
                (
                    "reconcile",
                    models.BooleanField(
                        blank=True, db_comment="Allow Reconciliation", null=True
                    ),
                ),
                (
                    "non_trade",
                    models.BooleanField(blank=True, db_comment="Non Trade", null=True),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True, db_comment="Created on", null=True
                    ),
                ),
                (
                    "write_date",
                    models.DateTimeField(
                        blank=True, db_comment="Last Updated on", null=True
                    ),
                ),
            ],
            options={
                "db_table": "account_account",
                "db_table_comment": "Account",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ResUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(blank=True, null=True)),
                ("create_date", models.DateTimeField(blank=True, null=True)),
                ("login", models.CharField()),
                ("password", models.CharField(blank=True, null=True)),
                (
                    "action_id",
                    models.IntegerField(
                        blank=True, db_comment="Home Action", null=True
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True, db_comment="Email Signature", null=True
                    ),
                ),
                (
                    "share",
                    models.BooleanField(blank=True, db_comment="Share User", null=True),
                ),
                (
                    "write_date",
                    models.DateTimeField(
                        blank=True, db_comment="Last Updated on", null=True
                    ),
                ),
                ("totp_secret", models.CharField(blank=True, null=True)),
                (
                    "tour_enabled",
                    models.BooleanField(blank=True, db_comment="Onboarding", null=True),
                ),
                ("notification_type", models.CharField(db_comment="Notification")),
                (
                    "odoobot_state",
                    models.CharField(
                        blank=True, db_comment="OdooBot Status", null=True
                    ),
                ),
                (
                    "odoobot_failed",
                    models.BooleanField(
                        blank=True, db_comment="Odoobot Failed", null=True
                    ),
                ),
                (
                    "property_warehouse_id",
                    models.JSONField(
                        blank=True, db_comment="Default Warehouse", null=True
                    ),
                ),
            ],
            options={
                "db_table": "res_users",
                "managed": False,
            },
        ),
    ]
