# Generated by Django 5.2.8 on 2025-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_code",
                    models.CharField(
                        blank=True, db_comment="Internal Reference", null=True
                    ),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, db_comment="Barcode", null=True),
                ),
                (
                    "combination_indices",
                    models.CharField(
                        blank=True, db_comment="Combination Indices", null=True
                    ),
                ),
                (
                    "standard_price",
                    models.JSONField(blank=True, db_comment="Cost", null=True),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        db_comment="Volume",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        db_comment="Weight",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(blank=True, db_comment="Active", null=True),
                ),
                (
                    "can_image_variant_1024_be_zoomed",
                    models.BooleanField(
                        blank=True,
                        db_comment="Can Variant Image 1024 be zoomed",
                        null=True,
                    ),
                ),
                (
                    "write_date",
                    models.DateTimeField(
                        blank=True, db_comment="Write Date", null=True
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True, db_comment="Created on", null=True
                    ),
                ),
                ("base_unit_count", models.FloatField(db_comment="Base Unit Count")),
                (
                    "lot_properties_definition",
                    models.JSONField(
                        blank=True, db_comment="Lot Properties", null=True
                    ),
                ),
            ],
            options={
                "db_table": "product_product",
                "db_table_comment": "Product Variant",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(blank=True, db_comment="Sequence", null=True),
                ),
                (
                    "color",
                    models.IntegerField(
                        blank=True, db_comment="Color Index", null=True
                    ),
                ),
                ("type", models.CharField(db_comment="Product Type")),
                ("service_tracking", models.CharField(db_comment="Create on Order")),
                (
                    "default_code",
                    models.CharField(
                        blank=True, db_comment="Internal Reference", null=True
                    ),
                ),
                ("name", models.JSONField(db_comment="Name")),
                (
                    "description",
                    models.JSONField(blank=True, db_comment="Description", null=True),
                ),
                (
                    "description_purchase",
                    models.JSONField(
                        blank=True, db_comment="Purchase Description", null=True
                    ),
                ),
                (
                    "description_sale",
                    models.JSONField(
                        blank=True, db_comment="Sales Description", null=True
                    ),
                ),
                (
                    "product_properties",
                    models.JSONField(blank=True, db_comment="Properties", null=True),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="Sales Price",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        db_comment="Volume",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        db_comment="Weight",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "sale_ok",
                    models.BooleanField(blank=True, db_comment="Sales", null=True),
                ),
                (
                    "purchase_ok",
                    models.BooleanField(blank=True, db_comment="Purchase", null=True),
                ),
                (
                    "active",
                    models.BooleanField(blank=True, db_comment="Active", null=True),
                ),
                (
                    "can_image_1024_be_zoomed",
                    models.BooleanField(
                        blank=True, db_comment="Can Image 1024 be zoomed", null=True
                    ),
                ),
                (
                    "has_configurable_attributes",
                    models.BooleanField(
                        blank=True, db_comment="Is a configurable product", null=True
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(blank=True, db_comment="Favorite", null=True),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        blank=True, db_comment="Created on", null=True
                    ),
                ),
                (
                    "write_date",
                    models.DateTimeField(
                        blank=True, db_comment="Last Updated on", null=True
                    ),
                ),
                (
                    "property_account_income_id",
                    models.JSONField(
                        blank=True, db_comment="Income Account", null=True
                    ),
                ),
                (
                    "property_account_expense_id",
                    models.JSONField(
                        blank=True, db_comment="Expense Account", null=True
                    ),
                ),
                (
                    "l10n_in_hsn_code",
                    models.CharField(blank=True, db_comment="HSN/SAC Code", null=True),
                ),
                (
                    "service_type",
                    models.CharField(blank=True, db_comment="Track Service", null=True),
                ),
                ("sale_line_warn", models.CharField(db_comment="Sales Order Line")),
                (
                    "expense_policy",
                    models.CharField(
                        blank=True, db_comment="Re-Invoice Costs", null=True
                    ),
                ),
                (
                    "invoice_policy",
                    models.CharField(
                        blank=True, db_comment="Invoicing Policy", null=True
                    ),
                ),
                (
                    "sale_line_warn_msg",
                    models.TextField(
                        blank=True, db_comment="Message for Sales Order Line", null=True
                    ),
                ),
                (
                    "website_size_x",
                    models.IntegerField(blank=True, db_comment="Size X", null=True),
                ),
                (
                    "website_size_y",
                    models.IntegerField(blank=True, db_comment="Size Y", null=True),
                ),
                (
                    "website_sequence",
                    models.IntegerField(
                        blank=True, db_comment="Website Sequence", null=True
                    ),
                ),
                (
                    "website_meta_og_img",
                    models.CharField(
                        blank=True, db_comment="Website opengraph image", null=True
                    ),
                ),
                (
                    "website_meta_title",
                    models.JSONField(
                        blank=True, db_comment="Website meta title", null=True
                    ),
                ),
                (
                    "website_meta_description",
                    models.JSONField(
                        blank=True, db_comment="Website meta description", null=True
                    ),
                ),
                (
                    "website_meta_keywords",
                    models.JSONField(
                        blank=True, db_comment="Website meta keywords", null=True
                    ),
                ),
                (
                    "seo_name",
                    models.JSONField(blank=True, db_comment="Seo name", null=True),
                ),
                (
                    "website_description",
                    models.JSONField(
                        blank=True, db_comment="Description for the website", null=True
                    ),
                ),
                (
                    "description_ecommerce",
                    models.JSONField(
                        blank=True, db_comment="eCommerce Description", null=True
                    ),
                ),
                (
                    "compare_list_price",
                    models.DecimalField(
                        blank=True,
                        db_comment="Compare to Price",
                        decimal_places=65535,
                        max_digits=65535,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        blank=True, db_comment="Is Published", null=True
                    ),
                ),
                (
                    "rating_last_value",
                    models.FloatField(
                        blank=True, db_comment="Rating Last Value", null=True
                    ),
                ),
                ("base_unit_count", models.FloatField(db_comment="Base Unit Count")),
                (
                    "sale_delay",
                    models.IntegerField(
                        blank=True, db_comment="Customer Lead Time", null=True
                    ),
                ),
                ("tracking", models.CharField(db_comment="Tracking")),
                (
                    "responsible_id",
                    models.JSONField(blank=True, db_comment="Responsible", null=True),
                ),
                (
                    "property_stock_production",
                    models.JSONField(
                        blank=True, db_comment="Production Location", null=True
                    ),
                ),
                (
                    "property_stock_inventory",
                    models.JSONField(
                        blank=True, db_comment="Inventory Location", null=True
                    ),
                ),
                (
                    "description_picking",
                    models.JSONField(
                        blank=True, db_comment="Description on Picking", null=True
                    ),
                ),
                (
                    "description_pickingout",
                    models.JSONField(
                        blank=True,
                        db_comment="Description on Delivery Orders",
                        null=True,
                    ),
                ),
                (
                    "description_pickingin",
                    models.JSONField(
                        blank=True, db_comment="Description on Receptions", null=True
                    ),
                ),
                (
                    "is_storable",
                    models.BooleanField(
                        blank=True, db_comment="Track Inventory", null=True
                    ),
                ),
                (
                    "lot_valuated",
                    models.BooleanField(
                        blank=True,
                        db_comment="Valuation by Lot/Serial number",
                        null=True,
                    ),
                ),
                (
                    "hs_code",
                    models.CharField(blank=True, db_comment="HS Code", null=True),
                ),
                (
                    "out_of_stock_message",
                    models.JSONField(
                        blank=True, db_comment="Out-of-Stock Message", null=True
                    ),
                ),
                (
                    "allow_out_of_stock_order",
                    models.BooleanField(
                        blank=True,
                        db_comment="Continue selling when out-of-stock",
                        null=True,
                    ),
                ),
                (
                    "show_availability",
                    models.BooleanField(
                        blank=True, db_comment="Show availability Qty", null=True
                    ),
                ),
                (
                    "available_threshold",
                    models.FloatField(
                        blank=True, db_comment="Show Threshold", null=True
                    ),
                ),
                (
                    "public_description",
                    models.JSONField(
                        blank=True, db_comment="Product Description", null=True
                    ),
                ),
                (
                    "available_in_pos",
                    models.BooleanField(
                        blank=True, db_comment="Available in POS", null=True
                    ),
                ),
                (
                    "to_weight",
                    models.BooleanField(
                        blank=True, db_comment="To Weigh With Scale", null=True
                    ),
                ),
                (
                    "asset_category_id",
                    models.JSONField(blank=True, db_comment="Asset Type", null=True),
                ),
                (
                    "deferred_revenue_category_id",
                    models.JSONField(
                        blank=True, db_comment="Deferred Revenue Type", null=True
                    ),
                ),
                (
                    "purchase_method",
                    models.CharField(
                        blank=True, db_comment="Control Policy", null=True
                    ),
                ),
                (
                    "purchase_line_warn",
                    models.CharField(db_comment="Purchase Order Line Warning"),
                ),
                (
                    "purchase_line_warn_msg",
                    models.TextField(
                        blank=True,
                        db_comment="Message for Purchase Order Line",
                        null=True,
                    ),
                ),
                (
                    "property_account_creditor_price_difference",
                    models.JSONField(
                        blank=True, db_comment="Price Difference Account", null=True
                    ),
                ),
                (
                    "service_to_purchase",
                    models.JSONField(
                        blank=True, db_comment="Subcontract Service", null=True
                    ),
                ),
                ("can_be_expensed", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "product_template",
                "db_table_comment": "Product",
                "managed": False,
            },
        ),
    ]
